@Library('jenkinsLibs') _
myDockerPipeline(
    rutaArchivoDocker: "02-primer-pipeline/Dockerfile",
    nombreImagenDocker: "ralburqueque11/homer_page:1.0.0-${BUILD_ID}",
    carpetaDocker: "02-primer-pipeline"
)
