@Library('jenkinsLibs') _
dockerPipeline(
    dockerfilePath: "02-primer-pipeline/Dockerfile",
    dockerImage: "ralburqueque11/homer_page:1.0.0-${BUILD_ID}",
    dockerContext: "02-primer-pipeline"
)
