@Library('jenkinsLibs') _
pipeline{
    agent any
    
    stages{
        stage("Construccion de docker"){
            steps{
                script{
                    myDockerLib.push(rutaArchivoDocker: "02-primer-pipeline/Dockerfile",
                                    nombreImagenDocker: "ralburqueque11/homer_page:1.0.0-${BUILD_ID}",
                                    carpetaDocker: "02-primer-pipeline");
                }
            }
           
        }
        stage("Pusheo de Docker"){
            steps{
                script{
                    myDockerLib.push(nombreImagenDocker: "ralburqueque11/homer_page:1.0.0-${BUILD_ID}");
                }
            }
            
        }
    }
}
